spring:
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}
      - nacos:application-${spring.profiles.active}
      - nacos:datasource-${spring.profiles.active}
  cloud:
    nacos:
      discovery:
        server-addr: ${witstalk.nacos.scheme}://${witstalk.nacos.server-addr}:8848
        group: ${spring.profiles.active}_GROUP
        namespace: ${witstalk.nacos.namespace}
        username: ${witstalk.nacos.username}
        password: ${witstalk.nacos.password}
      config:
        server-addr: ${witstalk.nacos.scheme}://${witstalk.nacos.server-addr}:8848
        group: ${spring.profiles.active}_GROUP
        namespace: ${witstalk.nacos.namespace}
        username: ${witstalk.nacos.username}
        password: ${witstalk.nacos.password}
        file-extension: yml
        # 共享配置（全局通用配置）
        shared-configs:
          - data-id: application-${spring.profiles.active}.yml
            group: ${spring.profiles.active}_GROUP
            refresh: true
          - data-id: datasource-${spring.profiles.active}.yml
            group: ${spring.profiles.active}_GROUP
            refresh: true
